export const AngerQuotes = [
    "Smile, breathe, and go slowly.",
    "Trust yourself. You've survived a lot, and you'll survive whatever is coming.",
    "Stress is an ignorant state. It believes that everything is an emergency. Nothing is that important.",
    "Anxiety does not empty tomorrow of its sorrows, but only empties today of its strength.",
    "You don't have to control your thoughts. You just have to stop letting them control you.",
    "Nothing diminishes anxiety faster than action.",
    "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.",
    "Anxiety is love's greatest killer. It makes others feel as you might when a drowning man holds on to you. You want to save him, but you know he will strangle you with his panic.",
    "Everything you have ever wanted, is sitting on the other side of fear.",
    "Do not let your difficulties fill you with anxiety; after all it is only in the darkest nights that stars shine more brightly.",
    "Anxiety is a thin stream of fear trickling through the mind. If encouraged, it cuts a channel into which all other thoughts are drained.",
    "Do not anticipate trouble, or worry about what may never happen. Keep in the sunlight.",
    "Anxiety's like a rocking chair. It gives you something to do, but it doesn't get you very far.",
    "You must learn to let go. Release the stress. You were never in control anyway.",
    "It's OKAY to be scared. Being scared means you're about to do something really, really brave",
    "Nothing can bring you peace but yourself.",
    "Just when the caterpillar thought the world was ending, he turned into a butterfly.",
    "Every time you are tempted to react in the same old way, ask if you want to be a prisoner of the past or a pioneer of the future.",
    "There are moments when all anxiety and stated toil are becalmed in the infinite leisure and repose of nature.",
    "Anxiety was born in the very same moment as mankind. And since we will never be able to master it, we will have to learn to live with it—just as we have learned to live with storms.",
    "No amount of anxiety can change the future. No amount of regret can change the past.",
    "Your mind will answer most questions if you learn to relax and wait for the answer.",
    "If you trade your authenticity for safety, you may experience the following: anxiety, depression, eating disorders, addiction, rage, blame, resentment, and inexplicable grief.",
    "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",
    "You have dug your soul out of the dark, you have fought to be here; do not go back to what buried you.",
    "No longer forward nor behind I look in hope and fear; But grateful take the good I find, The best of now and here.",
    "Not everything that weighs you down is yours to carry.",
    "Good humor is a tonic for mind and body. It is the best antidote for anxiety and depression. It is a business asset. It attracts and keeps friends. It lightens human burdens. It is the direct route to serenity and contentment.",
    "Difficult roads often lead to beautiful destinations. The best is yet to come.",
    "Hey you, keep living. It won't always be this overwhelming.",
    "If you want to conquer the anxiety of life, live in the moment, live in the breath.",
    "Do what you can, with what you've got, where you are.",
    "Nothing is permanent in this wicked world — not even our troubles.",
    "Sometimes the most important thing in a whole day is the rest taken between two deep breaths.",
    "We must be willing to let go of the life we've planned, so as to have the life that is waiting for us.",
    "If you can't fly, run. If you can't run, walk. If you can't walk, crawl, but by all means, keep moving.",
    "Keep walking through the storm. Your rainbow is waiting on the other side.",
    "Worry a little bit every day and in a lifetime you will lose a couple of years. If something is wrong, fix it if you can. But train yourself not to worry. Worry never fixes anything.",
    "Some days, doing 'the best we can' may still fall short of what we would like to be able to do, but life isn't perfect—on any front—and doing what we can with what we have is the most we should expect of ourselves or anyone else.",
    "Today's a perfect day for a whole new start. Let go of fear and free your mind. It's time to open your heart.",
    "You may not control all the events that happen to you, but you can decide not to be reduced by them.",
    "Whatever happens to you belongs to you. Make it yours. Feed it to yourself even if it feels impossible to swallow. Let it nurture you because it will.",
    "You wouldn't worry so much about what others think of you if you realized how seldom they do.",
    "When I let go of what I am, I become what I want to be.",
    "The elimination diet: Remove anger, regret, resentment, guilt, blame and worry. Then watch your health, and life, improve.",
    "Instead of worrying about what you cannot control, shift your energy to what you can create.",
    "If you can find a path with no obstacles, it probably doesn't lead anywhere.",
    "The best thing one can do when it is raining, is to let it rain.",
];