export const CuriousQuotes = [
    "No man ever prayed heartily without learning something.",
    "The highest activity a human being can attain is learning for understanding, because to understand is to be free.",
    "The main part of intellectual education is not the acquisition of facts, but learning how to make facts live.",
    "The past is a place of reference, not a place of residence; the past is a place of learning, not a place of living.",
    "Learning is a treasure that will follow its owner everywhere.",
    "A man who asks is a fool for five minutes. A man who never asks is a fool for life.",
    "I don't think much of a man who is not wiser today than he was yesterday.",
    "Never let formal education get in the way of your learning.",
    "To make no mistakes is not in the power of man; but from their errors and mistakes the wise and good learn wisdom for the future.",
    "Try to learn something about everything and everything about something.",
    "It is of practical value to learn to like yourself. Since you must spend so much time with yourself you might as well get some satisfaction out of the relationship.",
    "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young.",
    "Any fool can know. The point is to understand.",
    "A wise man can learn more from a foolish question than a fool can learn from a wise answer.",
    "Neither comprehension nor learning can take place in an atmosphere of anxiety.",
    "Learning is the beginning of wealth. Learning is the beginning of health. Learning is the beginning of spirituality. Searching and learning is where the miracle process all begins.",
    "Those who don't know history are doomed to repeat it.",
    "A good teacher can inspire hope, ignite the imagination, and instill a love of learning.",
    "Change is the end result of all true learning.",
    "I have been a teacher myself all my life. I have an intense passion to share with people. Our only salvation is in knowledge, in learning.",
    "We now accept the fact that learning is a lifelong process of keeping abreast of change. And the most pressing task is to teach people how to learn.",
    "The learning and knowledge that we have, is, at the most, but little compared with that of which we are ignorant.",
    "I am always ready to learn although I do not always like being taught.",
    "Some books leave us free and some books make us free.",
    "Don't just teach your children to read. Teach them to question what they read. Teach them to question everything.",
    "True teachers are those who use themselves as bridges over which they invite their students to cross; then, having facilitated their crossing, joyfully collapse, encouraging them to create their own.",
    "Whoso neglects learning in his youth, loses the past and is dead for the future.",
    "Study without desire spoils the memory, and it retains nothing that it takes in.",
    "Instruction does much, but encouragement everything.",
    "I don't love studying. I hate studying. I like learning. Learning is beautiful.",
    "The noblest pleasure is the joy of understanding.",
    "Education is the kindling of a flame, not the filling of a vessel.",
    "The great aim of education is not knowledge but action.",
    "One of the greatest and simplest tools for learning more and growing is doing more.",
    "He who is not everyday conquering some fear has not learned the secret of life.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "There is no school equal to a decent home and no teacher equal to a virtuous parent.",
    "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.",
    "Perfecting oneself is as much unlearning as it is learning.",
    "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
    "The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
    "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.",
    "You cannot open a book without learning something.",
    "Learn as though you would never be able to master it; hold it as though you would be in fear of losing it.",
    "The more I read, the more I acquire, the more certain I am that I know nothing.",
    "No problem can withstand the assault of sustained thinking.",
    "Education without application is just entertainment.",
    "For me, I am driven by two main philosophies: know more today about the world than I knew yesterday and lessen the suffering of others. You'd be surprised how far that gets you.",
    "Learn to light a candle in the darkest moments of someone's life. Be the light that helps others see; it is what gives life its deepest significance.",
    "Let the improvement of yourself keep you so busy that you have no time to criticize others.",
    "Never let hard lessons harden your heart; the hard lessons of life are meant to make you better, not bitter.",
    "Most of us must learn to love people and use things rather than loving things and using people.",
    "Failure is a bend in the road, not the end of the road. Learn from failure and keep moving forward.",
    "I have learned all kinds of things from my many mistakes. The one thing I never learn is to stop making them.",
    "The beautiful thing about learning is that nobody can take it away from you.",
    "One who has imagination without learning has wings without feet.",
    "You don't learn to walk by following rules. You learn by doing, and by falling over.",
    "I like to listen. I have learned a great deal from listening carefully. Most people never listen.",
    "Learning is not attained by chance. It must be sought for with ardor and attended with diligence.",
    "If you haven't learned the meaning of friendship, you haven't learned anything.",
    "Anyone who isn't embarrassed of who they were last year probably isn't learning enough.",
    "Each life is made up of mistakes and learning, waiting and growing, practicing patience and being persistent.",
    "In a time of drastic change it is the learners who inherit the future. The learned usually find themselves equipped to live in a world that no longer exists.",
    "The one thing that I keep learning over and over again is that I don't know nothing. I mean, that's my life lesson.",
    "And I believe that the best learning process of any kind of craft is just to look at the work of others.",
    "Everybody who is incapable of learning has taken to teaching.",
    "Every student can learn, just not on the same day, or the same way.",
    "Scholastic learning and polemical divinity retarded the growth of all true knowledge.",
    "Learning never exhausts the mind.",
    "When a poet digs himself into a hole, he doesn't climb out. He digs deeper, enjoys the scenery, and comes out the other side enlightened.",
    "Much learning does not teach understanding.",
    "Wisdom.... comes not from age, but from education and learning.",
    "That is what learning is. You suddenly understand something you've understood all your life, but in a new way.",
    "To know oneself is to study oneself in action with another person.",
    "Small minds have always lashed out at what they don't understand.",
    "For the things we have to learn before we can do them, we learn by doing them.",
    "In learning you will teach, and in teaching you will learn.",
    "While I thought that I was learning how to live, I have been learning how to die.",
    "Courage doesn't happen when you have all the answers. It happens when you are ready to face the questions you have been avoiding your whole life.",
    "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.",
    "Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.",
    "If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you.",
    "One of the reasons people stop learning is that they become less and less willing to risk failure.",
    "Develop a passion for learning. If you do, you will never cease to grow.",
    "The secret of success is learning how to use pain and pleasure instead of having pain and pleasure use you. If you do that, you're in control of your life. If you don't, life controls you.",
    "I am a woman in process. I'm just trying like everybody else. I try to take every conflict, every experience, and learn from it. Life is never dull.",
    "I am always doing that which I cannot do, in order that I may learn how to do it.",
    "Self-education is, I firmly believe, the only kind of education there is.",
    "Losers live in the past. Winners learn from the past and enjoy working in the present toward the future.",
    "Anything worth doing well is worth doing poorly at first.",
    "Study the past if you would define the future.",
    "We must learn to live together as brothers or perish together as fools.",
]
