export const DepressedQuotes = [
    "Please remember that you're capable, brave and loved - even when it feels like you're not.",
    "Do not give the past the power to define your future.",
    "Perhaps you've been assigned this mountain to show others that it can be moved.",
    "Just a reminder: it is NOT selfish to put your recovery first. Rather, it's necessary in order to make sure that everything else doesn't come last.",
    "Small, baby steps each day add up to huge, giant leaps over time. So, please keep going. Do NOT give up.",
    "You are not worthless, you are not a failure, and you are not a loser. That voice saying you are is just your depression trying to trick you.",
    "Even the darkest hour only has 60 minutes.",
    "Perhaps the butterfly is proof that you can go through a great deal of darkness yet become something beautiful again.",
    "Always try to end the day with a positive thought. No matter how hard things are, tomorrow is a fresh opportunity to make everything better.",
    "The World Health Organisation estimates that 350 million people suffer from depression worldwide. We know it may not seem like it, but you are NOT alone.",
    "Don't hate yourself for everything you aren't. Instead, love yourself for everything you are.",
    "Running away from your problems is a race you'll never win. Instead, reach out for help and try to confront them.",
    "Don't let your struggle become your identity. After all, you are so much more than just your illness.",
    "Be proud of who you are, instead of ashamed of how someone else sees you.",
    "Crying doesn't mean that you're weak. Since birth, it's always been a sign that you're alive.",
    "Don't dwell on those who hold you down. Instead, cherish those who helped you up.",
    "Never, ever, ever, ever, ever give up on yourself. As long as you keep on fighting, then you can beat your depression.",
    "Right now, stop whatever you're doing and think of all the things in life that you are grateful for. This is a really easy way to lift your mood!",
    "Even if you can't see any reason to keep on going, then it doesn't mean that there aren't any. It just means that in that moment, your depression is telling you even more lies than usual.",
    "Even the worst depressive episodes won't last forever.",
    "If you need a confidence booster, then remind yourself of all the difficult things you've endured and overcome.",
    "Don't ruin a good day by thinking about the possibility of a bad day in the future. Just enjoy the present moment :)",
    "As Confucius said, our greatest glory is not in never falling, but in rising every time we do.",
    "When your depression says, “Give up”, hope whispers, “Try one more time”.",
    "If you're worried about telling a friend that you struggle with depression, then remind yourself that you are one of 350 million people battling this illness. So, odds are that even if you don't know it, one or more of your friends are fighting depression too but are similarly scared to reach out to you.",
    "One day, if not already, your refusal to give up will inspire someone else.",
    "Please remember that having a bad day does not mean you have - or will have - a bad life.",
    "Hope is one of the most powerful emotions a person can have. Combine it with determination and there's no stopping you.",
    "In any given moment, we have two choices: to step forward into growth, or step backwards into safety. Stepping backwards may make us feel better in the short term, but stepping forwards will undoubtedly make us feel better in the long term.",
    "Never put the key to your happiness in someone else's pocket.",
    "Just because you're going through a rough patch, it doesn't mean you always will be. Recovery is possible. We promise you.",
    "Just because you have a mental illness, it doesn't mean that you are that illness. You're still a person - just like everybody else.",
    "Sometimes, you just need to cry your eyes out to be able to keep going. And you know what? That's OK.",
    "Listen to positive people and ignore negative ones. After all, people who doubt, judge and disrespect you are not worth your energy.",
    "Healing is a process, not an event. Give it time. Good things happen to those who never give up.",
    "Mental illness is NOT a life sentence.",
    "Don't be upset or caught up with things or people you cannot change. Instead, move on, let go, and concentrate on what you can change.",
    "When your depression tells you that it's impossible to be free of it, it is LYING!",
    "Today, do one little thing to take better care of yourself. Then, do it again tomorrow.",
    "When something goes wrong, take a moment to be thankful for all the things in your life that are going right.",
    "No-one ever injured their eyesight by looking on the bright side.",
    "You're allowed to scream. You're allowed to cry. You're allowed to fall apart. But you are not allowed to give up.",
    "Scars tell where we have been. They do not have to dictate where we are going.",
    "Remember, breakdowns can create breakthroughs. Sometimes, things fall apart so that other things can fall together.",
    "Never forget that you are worthy of love and respect.",
    "Sometimes you have to fight through your worst days in order to earn the best days of your life.",
    "Remember that life's greatest lessons are usually learned at the worst times and from the worst mistakes.",
    "You might be sad because you've been through a lot, but you should also be proud of yourself for being strong enough to make it through everything you've been through.",
    "When you say you suffer from a physical illness, you get sympathy. When you say you suffer from depression, you sometimes get blamed. We know it sucks, but at the very least, please take solace in the fact that you are not alone - as evidenced by the fact that 350 million people in the world struggle with depression.",
    "If someone doesn't respect you, appreciate you and value you, then they don't deserve you.",
    "If you're going through a hard time right now, make sure you do something today that makes you smile.",
    "When you're struggling with depression, it's really important to schedule some time in for daily self-care that gives you a lift.",
    "In the context of mental health, courage can be defined as the strength to ask for help.",
    "Starting today, stop keeping track of all the mistakes you've ever made. It's time to forgive yourself and start being your own best friend.",
    "Always look for something positive in each day ... even if some days you need to look a little harder than others.",
    "Things may seem gloomy ahead and you may feel like giving up, but if you don't keep going, then you will never know what is just around the corner.",
    "Never be ashamed of a scar. It simply means that you were stronger than whatever tried to hurt you.",
    "You are NOT your illness. You have an individual story to tell. You have a name, a history, a personality. Staying yourself is part of the battle.",
    "It is not weak to say, “I'm not OK, and I need help”. On the contrary, it is brave. It is courageous. And in the end, it could save your life.",
    "Whenever you find yourself doubting how far you can go, just remind yourself how far you have come. Remind yourself of everything you have faced, all the battles you have won, and all the fears you have overcome.",
    "No matter who gives up on you, don't you ever give up on yourself.",
    "Don't carry your mistakes around with you. Instead, place them under your feet and use them as stepping stones.",
    "Never stop doing your best just because someone doesn't give you credit for it.",
    "Sometimes the hardest part of the journey is believing you're worth the trip - but we're here to tell you that you are.",
    "Life is like a camera: focus on what's important, capture the good times, develop from the negatives, and if things don't work out, take another shot.",
    "Whatever you do, never forget that you're human. It's OK to have a meltdown. Just don't unpack and live there. Cry it out and then refocus on where you are heading.",
    "No one is ever too broken, too scarred or too far-gone to recover. If you keep on fighting, then anything's possible.",
    "Never let someone who doesn't know your value tell you how much you're worth.",
    "Never, ever forget that you are special, and that you touch more lives than you'll ever know.",
    "Maybe not today, tomorrow, or even in a year, but if you keep fighting and never give up, then things will eventually turn around, and you'll be able to look back with relief and shout, ‘Yes! I made it!'",
    "Never forget that walking away from something unhealthy is a very brave thing to do - even if you stumble a little on your way out the door.",
    "Depression is a war. Don't give up just because you lost a battle.",
    "Some days, life is all about your dreams, hopes and vision for the future. But on other days, all it's about is trying to put one foot in front of the other. And you know what? That's OK.",
    "Relationships are like glass - sometimes it's better to leave them broken than to hurt yourself trying to put them back together.",
    "MYTH: You will be depressed forever. FACT: With the right help, you can beat your depression and go on to live a happy, healthy, fulfilling life.",
    "Stop beating yourself up. You are a work in progress, which means you get there a little at a time, not all at once.",
    "If sometimes all you want is for someone to acknowledge just how difficult struggling with depression is, then here's your acknowledgement. We understand, and we're proud of you for not giving up.",
    "Someday, everything will make sense. So for now, laugh at the confusion, smile through the tears, and keep reminding yourself that everything happens for a reason.",
    "Don't compare your progress with that of others. After all, we all need our own time to travel our own distance.",
    "Finding the right therapist is a bit like dating ... sometimes you have to try a few before you find a good match.",
    "Don't change so people will like you. Be yourself and the right people will love the real you.",
    "Don't look back, because if you do, you might fall over what is in front of you.",
    "If you're thinking about giving up today, just live until tomorrow. And when you do, read this again.",
    "Just because your path is different, it doesn't mean you're lost.",
    "Recovery sometimes involves doing what you should do instead of what you want to do. But in the end, it is so, so worth it.",
    "You may have to fight a battle more than once to win it, but if you never give up, you will get there eventually.",
    "The past is like an anchor that holds you back. You have to be able to let go of who you were in order to become who you want to be.",
    "When you find the courage to let go of what you can't change, you'll take a giant leap forward in your quest to recover from depression.",
    "Hating yourself will never, ever get you as far as loving yourself will.",
    "Beautiful things happen when you distance yourself from negativity.",
    "The world will not end if you do not figure everything out tonight, so stop pacing, stop sweating, and stop fretting. Instead, go to bed and start again tomorrow.",
    "There comes a time when you have to stop crossing oceans for people who wouldn't jump puddles for you.",
    "When you focus on problems, you'll have more problems. When you focus on possibilities, you'll have more opportunities.",
    "No matter how far you've travelled down the wrong road, you can always turn around and get back on the right track.",
    "One of the most dangerous myths surrounding depression is that it is a life sentence, when in reality, if you seek the right help and keep on fighting, you CAN recover, and live a happy, healthy, depression-free life.",
    "When everything feels like an uphill struggle, just think of the view from the top.",
    "Life has many chapters, and one bad one does not mean that it's the end of the book.",
    "If you're feeling suicidal, write down your dreams. Block everything else out and picture them coming true. Use them as reasons to keep on fighting.",
    "Eat like you love yourself, move like you love yourself, speak like you love yourself, and act like you love yourself.",
    "Just because your life may not have turned out the way you'd planned, it doesn't mean that it won't turn out OK.",
    "It's hard for a person to beat depression, but it's even harder for depression to beat a person who never gives up.",
    "Being yourself is the prettiest thing you can be.",
    "No matter what you're going through right now, having a positive attitude is going to serve you better than having a negative one.",
    "Instead of counting your troubles, count all the joys you have in life as well.",
    "The most beautiful thing in the world is a smile that has struggled through tears.",
    "Recovery does not happen linearly. Sometimes you'll have bad days, sometimes you'll have setbacks, and sometimes you'll feel so low and broken that you'll want to give up. But if you keep taking little steps forward, you'll eventually get there.",
    "Depression isn't pretty, but having depression doesn't make you ugly. Anxiety is a burden, but having anxiety doesn't make you a burden. Even though you're struggling right now, you have nothing to be ashamed of. You are so, so much more than your problems, and you are a warrior for continuing to fight them.",
    "In case no one told you today: you are beautiful. You are loved. You are needed. You are alive for a reason. You are stronger than you think, and if you keep on fighting, then you're going to get through this.",
    "You were given this life because you are strong enough to live it.",
    "Don't compare the lowest points of your life to someone else's Instagram highlight real and use it as a reason to feel inadequate.",
    "Today, you don't need to have all the answers. You just need to know what to do next.",
    "If you do everything you can to keep on fighting, then even if they don't tell you, there'll be people who'll find your plight with depression inspiring.",
    "Don't be ashamed of the times you fell. Instead, be proud of all the times you got back up.",
    "In case you didn't know: studies show that 80% of the things we worry about happening never actually happen.",
    "Having depression is NOT a sign of weakness. It's a sign of being human, and anyone who tells you otherwise doesn't understand this illness.",
    "Guilt is toxic. Reliving the same mistake over and over again is torture. Constantly criticising and blaming yourself is bullying. Break free of this cycle. Reflect. Learn. Grow. Love yourself. Forgive yourself.",
    "Instead of always focusing on how far you have left to go, make sure you also remember how far you have come.",
    "This is just a little reminder that you deserve to be treated as well as you treat everybody else. Don't accept anything less!",
    "It is better to be an imperfect version of yourself than a perfect version of somebody else.",
    "Hope and depression are bitter rivals until one, always and inevitably, defeats the other.",
    "Someone failing to see the best in you does not diminish your worth as a person.",
    "Try not to get so comfortable with your demons that you accept them as being a part of you. Instead, seek help so that you can work on liberating yourself from them.",
    "Admitting that you're not OK is NOT a sign of weakness. It's a sign of self-awareness, maturity, and emotional strength.",
    "Making mistakes does not mean you've failed. Rather, it means you had the courage to try, and if you learn from those mistakes, then you'll soon succeed.",
    "Don't let negative, toxic, insecure people drag you down to their level.",
    "Is whatever you're frustrated about worth ruining the hour, the day, the week?",
    "We cannot in a minute get rid of unhealthy habits we've been practising for a lifetime. That's why it takes time for therapy to work.",
    "If you can't figure out where you stand with someone, then it might be time to stop standing and start walking.",
    "One day, you'll wake up and realise that the pain's still there but that it doesn't hurt quite as much as it used to. That's when you're on the road to healing.",
    "Try not to be discouraged by setbacks. Instead, try to be encouraged by the fact that you have the chance to overcome them.",
    "You deserve as much love and support as anybody else.",
    "Being imperfect doesn't mean you're unworthy. It means you're human.",
    "As Abraham Lincoln once said, if we magnified our successes as much as we magnified our disappointments, we'd all be much happier.",
    "Supportive, encouraging quotes - Like we've said, each day, The Depression Project emails over 50,000 people a supportive, encouraging quote to help them through their day - and this workbook includes some of the most popular ones!",
    "Cognitive behavioural therapy-based, fill-in-the-blank statements - This workbook's quotes are accompanied by CBT-based, fill-in-the-blank statements as well - to help you create your very own hopeful, uplifting, re-assuring reminders.",
    "Never make a permanent decision based on a temporary emotion.",
    "When I'm feeling depressed and anxious I tend to withdraw and isolate myself ... I can't reach out to those I love and feel worthless and a burden to them. When this happens, I then try to remember: 'your depression is trying to get you alone and then it will try to kill you'. This helps me remember that's it's my depression that's lying to me and keeping me from reaching out to those I love and who love me.",
    "Surviving is an achievement in and of itself. We've got to give ourselves more credit.",
    "I have a friend who is a psychiatrist. He always tells me, 'in the darkest night, the stars are still there, you just can't see them'.",
    "I try to remind myself that my current situation is not my final destination. I try to remind myself of the things I've already come through that I thought I would not make it through but I did.",
    "I make a point to remind myself: 'you will not get better with shame ... you will get better with love'.",
    "Just remember your success rate of getting though bad days is 100%.",
    "I have a tattoo of a bow & arrow as a reminder that when life pulls you back, it's just preparing to launch you into something great.",
    "This too shall pass. Got me through the deepest depression I have ever experienced.",
    "A full recovery is possible. Broken bones heal stronger.",
    "May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.", 
    "Hit the ground and choose to bounce back. We always have two options in every step of life so always choose to bounce back.",
    "You're braver than you believe, stronger than you seem, and smarter than you think.",
    "When my anxiety is really bad, I sing a Bob Marley song in my head over and over again: 'Don't worry about a thing, cause every little thing gonna be alright'.",
    "When you feel like you don't have the motivation or energy to do even the most basic of activities, remember that 1% beats 0% ... little wins pave the way for big wins.",
    "Normal is a cycle on the washing machine.",
    "A psych told me this many years ago and it has kept me going for many years. 'It's ok to feel s**t, give yourself the opportunity to feel s**t, don't fight it!' I learned over the years to give myself care time.",
    "Nothing in life is permanent. Don't let one bad thing ruin your whole day/week/month. If you can't change it, let it go and move on.",
    "Doing the best I can ... as long as I can.",
    "Everything will be okay in the end. If it's not okay, it's not the end!",
    "One foot in front of the other. Climb the ladder one step at a time. Believe in yourself, you can do this. The light at the end of the tunnel will come.",
]
