export const HappyQuotes = [
    "Happiness cannot be traveled to, owned, earned, worn or consumed. Happiness is the spiritual experience of living every minute with love, grace, and gratitude",
    "Some cause happiness wherever they go; others whenever they go.",
    "Be healthy and take care of yourself, but be happy with the beautiful things that make you, you.",
    "Most folks are about as happy as they make up their minds to be.",
    "For every minute you are angry you lose sixty seconds of happiness.",
    "The biggest adventure you can ever take is to live the life of your dreams.",
    "Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you.",
    "Everything has its wonders, even darkness and silence, and I learn, whatever state I may be in, therein to be content.",
    "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.",
    "Cry. Forgive. Learn. Move on. Let your tears water the seeds of your future happiness.",
    "The happiest people seem to be those who have no particular cause for being happy except that they are so.",
    "Every day is a new day.",
    "Beauty is everywhere. You only have to look to see it.",
    "You can't stop the waves, but you can learn to swim.",
    "Life is the dancer and you are the dance.",
    "Count your age by friends, not years. Count your life by smiles, not tears. ",
    "The point is not to pay back kindness but to pass it on.",
    "No medicine cures what happiness cannot.",
    "When you love what you have, you have everything you need.",
    "If you have only one smile in you give it to the people you love.",
    "Be faithful to that which exists within yourself.",
    "One of the best guides to how to be self-loving is to give ourselves the love we are often dreaming about receiving from others.",
    "The hardest challenge is to be yourself in a world where everyone is trying to make you be somebody else.",
    "Until you value yourself, you won't value your time. Until you value your time, you will not do anything with it.",
    "We are each gifted in a unique and important way. It is our privilege and our adventure to discover our own special light.",
    "Be the love you never received.",
    "How you love yourself is how you teach others to love you.",
    "Even when it seems that there is no one else, always remember there's one person who never ceased to love you - yourself.",
    "I am not bound to win, but I am bound to be true. I am not bound to succeed, but I am bound to live up to what light I have.",
    "To love yourself right now, just as you are, is to give yourself heaven. Don't wait until you die. If you wait, you die now. If you love, you live now.",
    "To be beautiful means to be yourself. You don't need to be accepted by others. You need to accept yourself.",
    "Trust yourself. You know more than you think you do.",
    "If you have the ability to love, love yourself first.",
    "As I began to love myself, I found that anguish and emotional suffering were only warning signs that I was living against my own truth.",
    "Our first and last love is self-love.",
    "You can receive all the compliments in the world, but that won't do a thing unless you believe it yourself.",
    "If you ever want to love someone, love yourself unconditionally first.",
    "You're always with yourself, so you might as well enjoy the company.",
    "You have to grow, you have to be, you have to love yourself unconditionally.",
    "The absence of self-love can never be replaced with the presence of people's love for you.",
];
