const heartbreakQuotes = [
    "Sometimes, good things fall apart so better things can fall together.",
    "Just because a relationship ends, it doesn't mean it's not worth having.",
    "Someday, it's gonna make sense.",
    "Starting today, I need to forget what's gone, appreciate what still remains, and look forward to what's coming next.",
    "Life always waits for some crisis to occur before revealing itself at its most brilliant.",
    "It just hurts a lot because it is healing.",
    "When you break up with someone, and I'm not talking casual breakups here, it's hard to take the sudden absence of such an important person in your life. It reminded me of when I'd stopped going to school and the weird uneasy feeling I'd gotten afterward like I was forgetting to do something. My life until that point had pivoted around some form of education, and all of a sudden, it was gone. Homework, classes, running around, and then –bam – nothing but a life of work stretching out before you. No one prepares you for that feeling or even mentions it. You just suddenly have a gap and have to decide how to fill it. A break-up is like that gap, only much, much more painful. One day the person you talked to constantly or did stuff with is just absent. Gone. Poof. And even though I'm not one of those people who has to be in a relationship all the time, I was feeling at a loss.",
    "Pain makes you stronger, fear makes you braver, heartbreak makes you wiser.",
    "I need to let go of this false hope that you will change your mind and come back to me.",
    "When I get sad, I stop being sad and be awesome instead.",
    "Dear heart, this is what happens when you try to make decisions on your own. Sincerely, Brain.",
    "Take a step back today, look at all those beautiful things you have.",
    "It's going to be okay, even if right now it feels like it the worst pain you have ever felt.",
    "It hurts to let go. Sometimes, it seems the harder you try to hold on to something or someone, the more it wants to get away. You feel like some kind of criminal for having felt, for having wanted. For having wanted to be wanted. It confuses you because you think that your feelings were wrong and it makes you feel so small because it's so hard to keep it inside when you let it out and it doesn't come back. You're left so alone that you can't explain. Damn, there's nothing like that, is there? I've been there and you have, too. You're nodding your head.",
    "Nothing in the universe can stop you from letting go and starting over.",
    "The course of true love did never run smooth.",
    "Hearts will never be practical until they are made unbreakable.",
    "Ever has it been that loves knows not its own depth until the hour of separation.",
    "It can be difficult to leave a long-term relationship, even when our inner-wisdom tells us it's time to let go. At this point, we can choose to let go and endure the intense pain of leaving behind the familiar to make way for a new chapter in our life. Or we can stay and suffer a low-grade pain that slowly eats away at our heart and soul, like emotional cancer. Until we wake up one day and realize we are buried so deep in the dysfunction of the relationship that we scarcely remember who we were and what we wanted and needed to be.",
    "Never allow someone to be your priority while allowing yourself to be their option.",
    "If you have ever, sir, been through a breakup of a romantic relationship that involved great love, you will perhaps understand what I experienced. There is in such situations usually a moment of passion during which the unthinkable is said; this is followed by a sense of euphoria at finally being liberated; the world seems fresh as if seen for the first time, then comes the inevitable period of doubt, the desperate and doomed backpedaling of regret; and only later, once emotions have receded, is one able to view with equanimity the journey through which one has passed.",
    "I don't know where I'm going, but I'm on my way.",
    "The hottest love has the coldest end.",
    "What's that line from T.S. Eliot? To arrive at the place where you started, but to know it for the first time. I'm able to write about a breakup from a different place. Same brokenness. Same rock-bottom. But a little more informed, now I'm older. Thank God for growing up.",
    "The heart was made to be broken.",
    "Failed relationships can be described as so much wasted make-up.",
    "Don't cry when the sun is gone because the tears won't let you see the stars.",
    "It's no good pretending that any relationship has a future if your record collections disagree violently or if your favorite films wouldn't even speak to each other if they met at a party.",
    "No matter how hard your heart is broken, the world doesn't stop for your grief.",
    "Sometimes we must undergo hardships, breakups, and narcissistic wounds, which shatter the flattering image that we had of ourselves, in order to discover two truths: that we are not who we thought we were; and that the loss of a cherished pleasure is not necessarily the loss of true happiness and well-being.",
    "When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us",
    "It is in your moments of decision that your destiny is shaped.",
    "Love is unconditional. Relationships are not.",
    "When we're incomplete, we're always searching for somebody to complete us. When, after a few years or a few months of a relationship, we find that we're still unfulfilled, we blame our partners and take up with somebody more promising. This can go on and on — series polygamy — until we admit that while a partner can add sweet dimensions to our lives, we, each of us, are responsible for our own fulfillment. Nobody else can provide it for us, and to believe otherwise is to delude ourselves dangerously and to program for eventual failure every relationship we enter.",
    "I never hated a man enough to give his diamonds back.",
    "Cheating and lying aren't struggles. They're reasons to break up.",
    "One day, they'll realize they lost a diamond while playing with worthless stones.",
    "Pain is inevitable. Suffering is optional.",
    "Be in love with your life. Every minute of it.",
    "Never love anybody that treats you like you're ordinary.",
    "When you leave, weary of me, without a word, I shall gently let you go.",
    "He's going to be sorry he lost you, so stop worrying. Forget the past, forget the pain, and remember what an incredible woman you are.",
    "We must be willing to let go of the life we've planned, so as to have the life that is waiting for us.",
    "I didn't lose you. You lost me. You'll search for me inside of everyone you're with and I won't be found.",
    "Lots of things can be fixed. Things can be fixed. But many times, relationships between people cannot be fixed, because they should not be fixed. You're aboard a ship setting sail, and the other person has joined the inland circus, or is boarding a different ship, and you just can't be with each other anymore. Because you shouldn't be.",
    "One day, I hope you look back at what we had and regret every single thing you did to let it end.",
    "I'm thankful for my struggle because without it I wouldn't have stumbled across my strength.",
    "The hardest thing is not talking to someone you used to talk to every day.",
    "I'm tired of fighting. For once, I want to be fought for.",
    "Cheer up, sweet, beautiful girl. You are going to be in love again and it will be magnificent.",
    "You made me feel like I was hard to love, and I will never forgive you for that.",
    "Letting go doesn't mean that you don't care about someone anymore. It's just realizing that the only person you really have control over is yourself.",
    "Even on my weakest days I get a little bit stronger",
    "Every woman that finally figured out her worth, has picked up her suitcases of pride and boarded a flight to freedom, which landed in the valley of change.",
    "Sometimes, you just have to accept the fact that some people only enter your life as a temporary happiness.",
    "I didn't stop loving you. I decided to stop showing it because no matter how hard I tried, you wouldn't get it.",
    "Every single day, do something that makes your heart sing.",
    "The hardest thing I'll ever do is walk away still loving you.",
    "Two words. Three vowels. Four consonants. Seven letters. It can either cut you open to the core and leave you in ungodly pain or it can free your soul and lift a tremendous weight off your shoulders. The phrase is: It's over.",
    "My life has become this one big 'I don't know.' ",
    "Get up, dress up, show up, and never give up.",
    "You'll always be my favorite 'what if.' ",
    "Trust that an ending is followed by a beginning.",
    "I tell you the past is a bucket of ashes, so live not in your yesterdays, nor just for tomorrow, but in the here and now. Keep moving and forget the post mortems; and remember, no one can get the jump on the future.",
    "The way they leave tells you everything.",
    "The toughest part of letting go is realizing the other person already did.",
    "Things to know about life: 'No' is a complete sentence. It does not require justification or explanation.",
    "I can feel myself slowly fading from your mind.",
    "One makes mistakes; that is life. But it is never a mistake to have loved.",
    "And one day, your name didn't make me smile anymore.",
    "No more tears, because I didn't lose you. You lost me.",
    "I wore your promise on my finger for one year, I'll wear your name on my heart till I die. Because you were my boy, you were my only boy forever.",
    "That's what happens. You let people in, and they destroy you.",
    "We started with a simple hello but ended with a complicated goodbye.",
    "I felt so much that I started to feel nothing.",
    "Don't be sorry. I trusted you. My fault, not yours.",
    "He put me through hell, and I called it love.",
    "The only thing I'm committed to right now is bettering myself.",
    "Bad things do happen; how I respond to them defines my character and the quality of my life. I can choose to sit in perpetual sadness, immobilized by the gravity of my loss, or I can choose to rise from the pain and treasure the most precious gift I have – life itself.",
    "Passivity means death, activity is living. If you are passive, you allow negative things to come into your life.",
    "Moving on, is a simple thing, what it leaves behind is hard.",
    "It's much more interesting to try and understand what binds two people together. Why we stay with each other is much more of a mystery than why we don't.",
    "Ask yourself, who would Columbus be today if he hadn't had the courage to lose sight of the shore back then?",
    "Watching you walk out of my life does not make me bitter or cynical about love. It makes me realize that if I wanted so much to be with the wrong person, how beautiful it will be when the right one comes along.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "In order to grow and to experience, one must leave his comfort zone. Very often this means that you have to do what you are afraid of in order to find what you didn't know you were looking for. This takes a lot of courage.",
    "Love is never lost. If not reciprocated, it will flow back and soften and purify the heart.",
    "I was never one to patiently pick up broken fragments and glue them together again and tell myself that the mended whole was as good as new. What is broken is broken, and I'd rather remember it as it was at its best, than mend it and see the broken pieces as long as I lived.",
    "The brightest future will always be based on a forgotten past, you can't go on well in life until you let go of your past failures and heartaches.",
    "Letting go has never been easy, but holding on can be as difficult. Yet strength is measured not by holding on, but by letting go.",
    "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face. You are able to say to yourself 'I have lived through this horror. I can take the next thing that comes along.' You must do the thing you think you cannot do.",
    "Was I bitter? Absolutely. Hurt? You bet your sweet ass I was hurt. Who doesn't feel a part of their heart break at rejection. You ask yourself every question you can think of, what, why, how come, and then your sadness turns to anger. That's my favorite part. It drives me, feeds me, and makes one hell of a story.",
    "The dreams break into a million tiny pieces. The dream dies. Which leaves you with a choice: you can settle for reality, or you can go off, like a fool, and dream another dream.",
    "I'm pretty horrible at relationships and haven't been in many long-term ones. Leaving and moving on – returning to a familiar sense of self-reliance and autonomy - is what I know; that feeling is as comfortable and comforting as it might be for a different kind of person to stay.",
    "I think a spiritual journey is not so much a journey of discovery. It's a journey of recovery. It's a journey of uncovering your own inner nature. It's already there.",
    "If you have to speculate if someone loves you and wants to be with you, chances are they don't. It's not that complicated. Love, in most cases, betrays the one feeling it. Don't waste moments waiting and wondering. Don't throw away your time dreaming of someone that doesn't want you. No one is that amazing, certainly not the one who would pass you up.",
    "In order to truly value loyalty, you must first endure the affliction of betrayal.",
    "Tragedy tears us apart sure, but it's your one chance to recreate yourself. You get to put yourself back together any way you want",
];

export const Heartbreak = {
    size: heartbreakQuotes.length,
    quotes: heartbreakQuotes
};
    