export const LoveQuotes = [
    "I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more.",
    "The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves.",
    "All, everything that I understand, I only understand because I love.",
    "It's a very dangerous state. You are inclined to recklessness and kind of tune out the rest of your life and everything that's been important to you. It's actually not all that pleasurable. I don't know who the hell wants to get in a situation where you can't bear an hour without somebody's company.",
    "The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart.",
    "To love is nothing. To be loved is something. But to love and be loved, that's everything.",
    "In order to be happy oneself it is necessary to make at least one other person happy.",
    "Maybe the only vow we ever need to offer the one we love is this: I will never, not for a sliver of a second, make you feel alone.",
    "There's no substitute for a great love who says, 'No matter what's wrong with you, you're welcome at this table.'",
    "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
    "I have decided to stick to love; hate is too great a burden to bear.",
    "Where there is love there is life.",
    "So, I love you because the entire universe conspired to help me find you.",
    "The best love is the kind that awakens the soul; that makes us reach for more, that plants the fire in our hearts and brings peace to our minds. That's what I hope to give you forever.",
    "And remember, as it was written, to love another person is to see the face of God.",
    "I would rather spend one lifetime with you, than face all the ages of this world alone.",
    "If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you.",
    "If I know what love is, it is because of you.",
    "Don't forget I'm just a girl, standing in front of a boy, asking him to love her.",
    "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.",
    "You have bewitched me body and soul, and I love, I love, I love you.",
    "Once I knew you I never wanted to know anyone else.",
    "Pleasure of love lasts but a moment. Pain of love lasts a lifetime.",
    "Love is like war: easy to begin but very hard to stop.",
    "I never want to stop making memories with you.",
    "We were together. I forget the rest.",
    "P.S. I love you.",
    "I love you past the moon and miss you beyond the stars.",
    "The greatest thing you'll ever learn Is to love and be loved in return.",
    "And in the end, the love you take, is equal to the love you make.",
    "All of me loves all of you.",
    "However far away, I will always love you. However long I stay, I will always love you. Whatever words I say, I will always love you. I will always love you.",
    "You and me together, through the days and nights. I don't worry 'cause everything's gonna be alright.",
    "It was always you.",
    "And when you're needing your space to do some navigating, I'll be here patiently waiting to see what you find.",
    "Before the day I met you, life was so unkind. But you're the key to my peace of mind.",
    "I love you more than I have ever found a way to say to you.",
    "You give me the most gorgeous sleep that I've ever had.",
    "All you need is love. But a little chocolate now and then doesn't hurt.",
    "I still haven't figured out how to sit across from you, and not be madly in love with everything you do.",
    "I swear I couldn't love you more than I do right now, and yet I know I will tomorrow.",
    "We are shaped and fashioned by those we love.",
    "You know it's love when all you want is that person to be happy, even if you're not part of their happiness.",
    "You don't love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear.",
    "'Tis better to have loved and lost than never to have loved at all.",
    "There is a madness in loving you, a lack of reason that makes it feel so flawless.",
    "She knew she loved him when 'home' went from being a place to being a person.",
    "Make sure you marry someone who laughs at the same things you do.",
    "How strange to dream of you even when I am wide awake.",
    "I love that you are my person and I am yours, that whatever door we come to, we will open it together.",
    "I was, and I remain, utterly and completely and totally in love with you.",
];
