export const SadQuotes = [
    "Strength doesn't come from what you can do. It comes from overcoming the things you once thought you couldn't.",
    "You may encounter many defeats, but you must not be defeated. In fact, it may be necessary to encounter the defeats, so you can know who you are, what you can rise from, how you can still come out of it.",
    "The only way to do great work is to love what you do.",
    "Difficulties in life are intended to make us better, not bitter.",
    "The gem cannot be polished without friction, nor man perfected without trials.",
    "Believe you can and you're halfway there.", 
    "Don't watch the clock; do what it does. Keep going.", 
    "When you come out of the storm, you won't be the same person who walked in. That's what the storm is all about.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Fall seven times, stand up eight.",
    "Life is 10% what happens to us and 90% how we react to it.", 
    "The harder the conflict, the greater the triumph.", 
    "You are never too old to set another goal or to dream a new dream.", 
    "Perseverance is not a long race; it is many short races one after the other.",
    "Do not wait for leaders; do it alone, person to person.", 
    "A winner is just a loser who tried one more time.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart",
    "Our greatest glory is not in never falling, but in rising every time we fall.", 
    "If you're going through hell, keep going.", 
    "The world breaks everyone, and afterward, some are strong at the broken places.",
    "Your time is limited, don't waste it living someone else's life.", 
    "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.", 
    "Success is not final, failure is not fatal: It is the courage to continue that counts.", 
    "Don't let yesterday take up too much of today.", 
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", 
    "The only way out of the labyrinth of suffering is to forgive.", 
    "You miss 100% of the shots you don't take.", 
    "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks.", 
    "The future depends on what you do today.", 
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "I am thankful for my struggle because without it I wouldn't have come across my strength.",
    "Never be ashamed of a scar. It means you were stronger than whatever tried to hurt you.",
    "Once you choose hope, anything is possible.",
    "Until you're broken you don't know what you're made of. It gives you the ability to build yourself all over again, but stronger than ever…",
    "Owning your story is the bravest thing you'll ever do.",
    "There is a difference between giving up and knowing when you've had enough.",
    "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path." ,
    "Our greatest glory is not in never falling but in rising every time we fall.",
    "The most beautiful people I've known are those who have known trials, have known struggles, have known loss, and have found their way out of the depths.",
    "Even the darkest night will end and the sun will rise.",
    "As I look back on my life, I realize that every time I thought I was being rejected from something good, I was actually being re-directed to something better.",
    "Respect yourself enough to say 'I deserve peace' and walk away from people or things that prevent you from attaining it.",
    "You can't start the next chapter of your life if you keep re-reading the last one.",
    "Every day may not be good, but there is some good in every day.",
    "One of the happiest moments in life is when you find the courage to let go of what you cannot change.",
    "Stop focusing on how stressed you are and remember how blessed you are.",
    "Anyone can give up; it is the easiest thing in the world to do. But to hold it together when everyone would expect you to fall apart, now that is true strength.",
    "Every experience, no matter how bad it seems, holds within it a blessing of some kind. The goal is to find it.",
    "I survived because the fire inside me burned brighter than the fire around me.",
    "Your hardest times often lead to the greatest moments of your life. Keep going. Tough situations build strong people in the end.",
    "The struggle you're in today is developing the strength you need for tomorrow. Don't give up.",
    "Talk to yourself like you would to someone you love.",
    "Whenever you feel down, remember it is always daylight somewhere on this rock we call Earth. Whenever you are belittled by a human, remember that she or he does not represent the whole for the Earth is way bigger than any puny creature you may encounter.",
    "You never know how strong you are until being strong is the only choice you have.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    "A diamond is a chunk of coal that did well under pressure.",
    "Life's challenges are not supposed to paralyze you; they're supposed to help you discover who you are.",
    "Never apologize for being sensitive or emotional. Let this be a sign that you've got a big heart and aren't afraid to let others see it. Showing your emotions is a sign of strength.",
    "When something bad happens, you have three choices: You can either let it define you, let it destroy you or let it strengthen you.",
    "I can be changed by what happens to me. But I refuse to be reduced by it.",
    "We don't develop courage by being happy every day. We develop it by surviving difficult times and challenging adversity.",
    "Worrying doesn't empty tomorrow of its sorrows; it empties today of its strengths.",
    "Owning your story is the bravest thing you'll ever do.",
]